### ISSUE TITLE
En tant qu'utilisateur, je veux pouvoir utiliser ma compétence spéciale

### ISSUE THREAD

**Issue by bastienrobert** [bastienrobert/la-ferme#53]
**Description**
La compétence ne doit pouvoir être utilisée qu'une fois.

- [ ] Portable : découvrir le lieu d'un autre joueur (#49)
- [ ] Happy : jouer deux fois (#50)
- [ ] Enceinte : annuler une carte "coup de boule" (uncivil) (#51)
- [ ] Baton : renvoyer le malus vers un autre joueur (#52)

**Figma**
22
